// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-variants/CourseMarketplace.tsx": () => import("../components/mockups/homepage-variants/CourseMarketplace.tsx"),
  "./components/mockups/homepage-variants/ImmersiveSplit.tsx": () => import("../components/mockups/homepage-variants/ImmersiveSplit.tsx"),
  "./components/mockups/homepage-variants/PathDiscovery.tsx": () => import("../components/mockups/homepage-variants/PathDiscovery.tsx"),
  "./components/mockups/homepage-variants/TeacherCommunity.tsx": () => import("../components/mockups/homepage-variants/TeacherCommunity.tsx")
};
